filegroup(
    name = "trade-data",
    srcs = [
            "CITIES_data.csv",
            "country_region_mapping.csv",
            "purposes.csv",
            "schema.gql",
            "trade_terms.csv",
            "units.csv"
        ],
    visibility = ["//visibility:public"]
)